esphome:
  name: esphome-web-4f99e4
  friendly_name: DISPLAY 1
  min_version: 2025.5.0
  name_add_mac_suffix: false

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password